services:

  postgres-user-info:
    container_name: postgres-user-info
    image: postgres
    volumes:
      - postgres-user-info-data:/data/postgres
    environment:
      POSTGRES_USER: dimasik666
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_info_db
    ports:
      - "5433:5432"
    networks:
      - postgres-network
    restart: unless-stopped

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Expose port for pgAdmin
    networks:
      - postgres-network
    depends_on:
      - postgres-user-info

volumes:
  postgres-user-info-data:

networks:
  postgres-network:
    external: true

# api gateway
#  api-gateway-oauth-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: ./src/main/resources/.env
#    container_name: api-gateway-oauth-service
#    ports:
#      - "8080:8080"
##    depends_on:
##      - consul
##      - postgres
#    environment:
#      OAUTH-GOOGLE-CLIENT-ID: ${GOOGLE_CLIENT_ID}
#      OAUTH-GOOGLE-CLIENT-SECRET: ${GOOGLE_CLIENT_SECRET}
#      CONSUL-HOST: ${CONSUL_HOST}
#      CONSUL-PORT: ${CONSUL_PORT}
#      REDIRECT-URL: ${GOOGLE_REDIRECT_URI}


#volumes:
#  postgres_data: